package com.marsa.absen.ui.theme

import androidx.compose.ui.graphics.Color

// Palet cadangan (dipakai jika HP < Android 12 atau dynamic color dimatikan)
val PrimaryLight = Color(0xFF006A6A)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF9CF1F0)
val OnPrimaryContainerLight = Color(0xFF002020)
val SecondaryLight = Color(0xFF4A6363)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E7)
val OnSecondaryContainerLight = Color(0xFF051F1F)
val TertiaryLight = Color(0xFF4B607C)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFD3E4FF)
val OnTertiaryContainerLight = Color(0xFF041C35)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF4FBFA)
val OnBackgroundLight = Color(0xFF161D1D)
val SurfaceLight = Color(0xFFF4FBFA)
val OnSurfaceLight = Color(0xFF161D1D)
val SurfaceVariantLight = Color(0xFFDAE5E4)
val OnSurfaceVariantLight = Color(0xFF3F4948)
val OutlineLight = Color(0xFF6F7979)

val PrimaryDark = Color(0xFF80D5D4)
val OnPrimaryDark = Color(0xFF003737)
val PrimaryContainerDark = Color(0xFF004F4F)
val OnPrimaryContainerDark = Color(0xFF9CF1F0)
val SecondaryDark = Color(0xFFB0CCCB)
val OnSecondaryDark = Color(0xFF1B3534)
val SecondaryContainerDark = Color(0xFF324B4B)
val OnSecondaryContainerDark = Color(0xFFCCE8E7)
val TertiaryDark = Color(0xFFB3C8E8)
val OnTertiaryDark = Color(0xFF1C314B)
val TertiaryContainerDark = Color(0xFF334863)
val OnTertiaryContainerDark = Color(0xFFD3E4FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val BackgroundDark = Color(0xFF0E1514)
val OnBackgroundDark = Color(0xFFDDE4E3)
val SurfaceDark = Color(0xFF0E1514)
val OnSurfaceDark = Color(0xFFDDE4E3)
val SurfaceVariantDark = Color(0xFF3F4948)
val OnSurfaceVariantDark = Color(0xFFBEC9C8)
val OutlineDark = Color(0xFF899392)
